development:
  adapter: postgresql
  encoding: utf8
  database: booking_development
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: booking_test
  username:
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: booking_production
  username:
  password:
  host: localhost
